In [10]:
import os
import pyreadr as pyr
import pandas as pd
import numpy as np
import plotly.express as px
from pathlib import Path

### Introducción a Python

In [2]:
nombre = 'Juan Camilo'
num = 3
decimal =2.15
condicion = True

In [3]:
### Imprimir el tipo de una variable
print(type(nombre))

<class 'str'>

In [4]:
print('Hello World!')

Hello World!

In [5]:
print(f'Mi nombre es {nombre}')

Mi nombre es Juan Camilo

In [6]:
print(f'La variable num es {num}')

La variable num es 3

In [7]:
print(f'La variable num es {condicion}')

La variable num es True

### Introducción a las listas

In [8]:
beatles = ['John', 'Paul', 'George', 'Ringo']
print(beatles)
print(type(beatles))

['John', 'Paul', 'George', 'Ringo']
<class 'list'>

In [9]:
notas_taller = [4.2, 3.8, 4.5, 2, 5]
print(notas_taller)

[4.2, 3.8, 4.5, 2, 5]

In [11]:
random_list = ['mytext', 3.0, 7, [10, 20]]
print(random_list)

['mytext', 3.0, 7, [10, 20]]

In [12]:
notas_taller.append(5)
print(notas_taller)

[4.2, 3.8, 4.5, 2, 5, 5]

In [13]:
### Acceder al primer elemento de la lista
beatles[0]

'John'

In [14]:
### Tamaño de la lista
len(beatles)

4

### Diccionarios como estructuras de datos en Python

In [15]:
diccionario = {'nombre':'Fabián', 
               'semestre':'3', 
               'carrera':'economía', 
               'maestría':True}

In [16]:
diccionario['nombre']

'Fabián'

In [17]:
'nombre' in diccionario

True

In [18]:
diccionario.keys()

dict_keys(['nombre', 'semestre', 'carrera', 'maestría'])

In [19]:
diccionario['carrera'] = 'Estadística'

In [20]:
diccionario

{'nombre': 'Fabián',
 'semestre': '3',
 'carrera': 'Estadística',
 'maestría': True}

### Introducción a los condicionales

In [21]:
lado_oscuro = 'Anakin Skywalker'
hijo = 'Luke Skywalker'

In [22]:
if lado_oscuro == 'Anakin Skywalker':
    print('Darth Vader')

if lado_oscuro == hijo:
    print('Luke, no te rindas al odio. Eso lleva al lado oscuro')

Darth Vader

In [23]:
if lado_oscuro == 'hijo':
    print('Luke, no te rindas al odio. Eso lleva al lado oscuro')
else:
    print(lado_oscuro + 'es el padre de' + hijo)

Anakin Skywalkeres el padre deLuke Skywalker

### Introducción a los bucles

In [24]:
for i in range(0, 5):
    print(i)

0
1
2
3
4

In [25]:
for i in range(3, 8, 2):
    print(i)

3
5
7

In [26]:
for i in 'Python':
    print(i)

P
y
t
h
o
n

In [27]:
mago = ["Harry", "Hermione", "Ron", "Voldemort", "Dumbledore"]

for i in mago:
    if i == 'Voldemort':
        break
    print(i)

Harry
Hermione
Ron

In [ ]:
def nombre_funcion(parametro1, parametro2, ...):
    """
    Descripción de lo que hace la función

    Parameters:
        parametro1 (clase_parametro1): Descripción del primer parámetro.
        parametro2 (clase_parametro2): Descripción del segundo parámetro.

    Returns:
        output1 (clase_output): Descripción de lo que es el producto y qué valores puede tomar.
    """

    # Bloque de código
    
    return(resultado)

In [28]:
def suma_dos_numeros(a, b):
    """
    Esta función toma dos números y entrega la suma de estos.

    Parameters:
        a (float): número a sumar.
        b (float): número a sumar.

    Returns:
        resultado (float): suma de a + b
    """
    resultado = a + b

    return(resultado)

In [29]:
suma_dos_numeros(1, 2)

3

### Introducción a Pandas

In [33]:
df = pd.read_csv('../data/adult.csv')
df = df.drop(columns = ['Unnamed: 0'])
df.head(5)

,age,workclass,fnlwgt,education,education num,marital status,occupation,relationship,race,sex,capital gain,capital loss,hours per week,native country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [34]:
df.tail(5)

,age,workclass,fnlwgt,education,education num,marital status,occupation,relationship,race,sex,capital gain,capital loss,hours per week,native country,income
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education num   32561 non-null  int64
 5   marital status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital gain    32561 non-null  int64
 11  capital loss    32561 non-null  int64
 12  hours per week  32561 non-null  int64
 13  native country  32561 non-null  str
 14  income          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

In [36]:
df.describe()

,age,fnlwgt,education num,capital gain,capital loss,hours per week
count,32561.000000,3.256100e+04,32561.000000,32561.000000,32561.000000,32561.000000
mean,38.581647,1.897784e+05,10.080679,1077.648844,87.303830,40.437456
std,13.640433,1.055500e+05,2.572720,7385.292085,402.960219,12.347429
min,17.000000,1.228500e+04,1.000000,0.000000,0.000000,1.000000
25%,28.000000,1.178270e+05,9.000000,0.000000,0.000000,40.000000
50%,37.000000,1.783560e+05,10.000000,0.000000,0.000000,40.000000
75%,48.000000,2.370510e+05,12.000000,0.000000,0.000000,45.000000
max,90.000000,1.484705e+06,16.000000,99999.000000,4356.000000,99.000000

In [37]:
### Renombrando las columnas
df.rename(columns = {'education num':'education_num',
                   'marital status':'marital_tatus',
                   'capital gain': 'capital_gain',
                   'capital loss': 'capital_loss',
                   'hours per week': 'hours_per_week',
                   'native country': 'native_country'}, 
                   inplace = True)

### Usando iloc

In [40]:
### En el siguiente ejemplo se ubican las filas desde la 10 hasta la 20 y las dos primera columnas

df.iloc[10:21, :2]

    age         workclass
10   37           Private
11   30         State-gov
12   23           Private
13   32           Private
14   40           Private
15   34           Private
16   25  Self-emp-not-inc
17   32           Private
18   38           Private
19   43  Self-emp-not-inc
20   40           Private

### Usando loc

In [41]:
### Localizar filas de acuerdo a una condición
### Obtener las filas en las que los años de educación sean iguales a 16

df.loc[df['education_num'] == 16]

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
20,40,Private,193524,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
63,42,Private,116632,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,45,United-States,>50K
89,43,Federal-gov,410867,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,>50K
96,48,Self-emp-not-inc,191277,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,1902,60,United-States,>50K
189,58,State-gov,109567,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,1,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32429,51,Local-gov,203334,Doctorate,16,Divorced,Exec-managerial,Not-in-family,White,Female,0,0,45,United-States,>50K
32469,58,Self-emp-inc,181974,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Female,0,0,99,?,<=50K
32470,50,Private,485710,Doctorate,16,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,50,United-States,<=50K
32532,34,Private,204461,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,60,United-States,>50K
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K

In [42]:
#Ejercicio: Encontrar las personas cuyo trabajo por horas sea igual o mayor a 45
df.loc[df['hours_per_week'] >= 45]

,age,workclass,fnlwgt,education,education_num,marital_tatus,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
13,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
15,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32538,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32543,45,Local-gov,119199,Assoc-acdm,12,Divorced,Prof-specialty,Unmarried,White,Female,0,0,48,United-States,<=50K
32548,65,Self-emp-not-inc,99359,Prof-school,15,Never-married,Prof-specialty,Not-in-family,White,Male,1086,0,60,United-States,<=50K
32550,43,Self-emp-not-inc,27242,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,50,United-States,<=50K
32552,43,Private,84661,Assoc-voc,11,Married-civ-spouse,Sales,Husband,White,Male,0,0,45,United-States,<=50K